### ISSUE TITLE
Minor fixes needed in Hello Proskomma Tutorial

### ISSUE THREAD

**Issue by JakeKyle** [Proskomma/proskomma-docs#1]
Very informative and helpful tutorial. Just a couple of minor things needed fixing in code given for it to work:

A missing close bracket in this line (repeated):

```
let content = fse.readFileSync(path.resolve(__dirname, './psa.usfm').toString();
```

addDocument needed a "tags" argument.

**Comment by mvahowe** [comment]
Thanks @JakeKyle! I've fixed the typo. I don't think that the tags argument should be required for addDocument so I've removed that from Proskomma. (I think it crept in during a recent refactoring of the schema.) I'll update the auto-generated schema doc shortly.
